In [11]:
from src.Sem3Py.Numerical import Interpolation as intp

import numpy as np

In [12]:
x = [8, 9, 9.5, 11]
y = [2.079422, 2.197225, 2.251292, 2.3979]

In [13]:
k = intp(x, y)

In [15]:
k.lagrange(9.2)

2.2192085999999995

In [16]:
cf, p = k.newton_dd(9.2)

In [17]:
print(cf, p)

[[ 2.07942200e+00  1.17803000e-01 -6.44600000e-03  4.16111111e-04]
 [ 2.19722500e+00  1.08134000e-01 -5.19766667e-03  0.00000000e+00]
 [ 2.25129200e+00  9.77386667e-02  0.00000000e+00  0.00000000e+00]
 [ 2.39790000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 2.2192085999999995


In [4]:
import numpy as np


In [14]:
u5 = lambda funcs: (funcs[1] + funcs[3] + funcs[4] + funcs[6])/4

u7 = lambda funcs: (funcs[3] + funcs[6] + 1)/4

u9 = lambda funcs: (funcs[5] + funcs[7] + 23)/4

u1 = lambda funcs: (funcs[2] + funcs[0] + 0.5)/4

u3 = lambda funcs: (funcs[1] + funcs[4] + 14.5)/4

u2 = lambda funcs: (funcs[0] + funcs[1] + funcs[3] + 2)/4

u4 = lambda funcs: (funcs[0] + funcs[3] + funcs[5])/4

u6 = lambda funcs: (funcs[2] + funcs[7] + funcs[4] + 12)/4

u8 = lambda funcs: (funcs[6] + funcs[7] + funcs[4] + 4)/4



funcs = [u1, u2, u3, u4, u5, u6, u7, u8, u9]
init = [33/16, 278/64, 113/16, 178/64, 25/4, 558/64, 45/16, 362/64, 153/16]
init


[2.06, 4.34, 7.06, 2.78, 6.25, 8.72, 2.81, 5.66, 9.56]

In [17]:
u1 = lambda funcs: (funcs[0] + funcs[1] + 3)/4
u2 = lambda funcs: (funcs[0] + funcs[2] + 16)/4
u3 = lambda funcs: (funcs[0] + funcs[2] + 4)/4
u4 = lambda funcs: (funcs[1] + funcs[2] + 19)/4

funcs = [u1, u2, u3, u4]
init = [0, 0, 0, 0]

In [18]:
delta = 0.01
%precision 2


arr1 = init
arr2 = init
flag = False
itn = 1
temp = []
        
while len(temp) < len(arr1):

                
    temp_arr2 = []
    for i in range(len(funcs)):
        temp_arr = []
        for j in range(len(funcs)):
            if i != j:
                temp_arr.append(arr1[j])
                
        temp_arr2.append(funcs[i](temp_arr))
                               
    arr2 = np.vstack([arr2, np.around(temp_arr2, decimals=2)])
    arr1 = temp_arr2
                        
    ls = [abs((arr2[itn, i] - arr2[itn-1, i])/arr2[itn, i]) for i in range(len(arr1))]

    temp = []

    for val in ls:
        if val < delta:
            temp.append(0)
                    
    itn += 1

print(arr2)

[[0.   0.   0.   0.  ]
 [0.75 4.   1.   4.75]
 [2.   5.38 2.38 6.  ]
 [2.69 6.   3.   6.69]
 [3.   6.34 3.34 7.  ]
 [3.17 6.5  3.5  7.17]
 [3.25 6.59 3.59 7.25]
 [3.29 6.62 3.62 7.29]
 [3.31 6.65 3.65 7.31]]
