In [11]:
from src.Sem3Py.Numerical import Interpolation as intp

import numpy as np

In [12]:
x = [8, 9, 9.5, 11]
y = [2.079422, 2.197225, 2.251292, 2.3979]

In [13]:
k = intp(x, y)

In [15]:
k.lagrange(9.2)

2.2192085999999995

In [16]:
cf, p = k.newton_dd(9.2)

In [17]:
print(cf, p)

[[ 2.07942200e+00  1.17803000e-01 -6.44600000e-03  4.16111111e-04]
 [ 2.19722500e+00  1.08134000e-01 -5.19766667e-03  0.00000000e+00]
 [ 2.25129200e+00  9.77386667e-02  0.00000000e+00  0.00000000e+00]
 [ 2.39790000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 2.2192085999999995
