In [11]:
from src.Sem3Py.Numerical import Interpolation as intp

import numpy as np

In [12]:
x = [8, 9, 9.5, 11]
y = [2.079422, 2.197225, 2.251292, 2.3979]

In [13]:
k = intp(x, y)

In [15]:
k.lagrange(9.2)

2.2192085999999995

In [16]:
cf, p = k.newton_dd(9.2)

In [17]:
print(cf, p)

[[ 2.07942200e+00  1.17803000e-01 -6.44600000e-03  4.16111111e-04]
 [ 2.19722500e+00  1.08134000e-01 -5.19766667e-03  0.00000000e+00]
 [ 2.25129200e+00  9.77386667e-02  0.00000000e+00  0.00000000e+00]
 [ 2.39790000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]] 2.2192085999999995


In [12]:
u5 = lambda funcs: (25)/4

u7 = lambda funcs: (funcs[4] + 5)/4

u9 = lambda funcs: (funcs[4] + 32)/4

u1 = lambda funcs: (funcs[3] + 2)/4

u3 = lambda funcs: (funcs[3] + 22)/4

u2 = lambda funcs: (funcs[0] + funcs[1] + funcs[3] + 2)/4

u4 = lambda funcs: (funcs[0] + funcs[3] + funcs[5] + 0)/4

u6 = lambda funcs: (funcs[2] + funcs[7] + funcs[4] + 12)/4

u8 = lambda funcs: (funcs[6] + funcs[7] + funcs[4] + 4)/4



funcs = [u1, u2, u3, u4, u5, u6, u7, u8, u9]

In [13]:
from src.Sem3Py.Numerical import Solutions as sln

In [18]:
k = sln([], [])

#%precision 2

print(k.gauss_seidel(funcs, [33/16, 278/64, 113/16, 178/64, 25/4, 558/64, 45/16, 362/64, 153/16], 0.01))

[[2.06 4.34 7.06 2.78 6.25 8.72 2.81 5.66 9.56]
 [2.06 4.34 7.06 2.78 6.25 8.72 2.81 5.66 9.56]]
